let suggestions = [
    "Abhaipur	AHA	",
    "Abhayapuri Asam	AYU	",
    "Abohar	ABS	",
    "Abu Road	ABR",
    "Achalda	ULD	",
    "Adas Road	ADD",
    "Adavali	ADVI",
    "Adesar	AAR	",
    "Adgaon Buzurg	ABZ	",
    "Adhartal	ADTL	",
    "Adhikari	ADQ	",
    "Adi Saptagram	 ADST",
    "Adilabad	ADB	",
    "Adina	ADF	",
    "Adipur	AI",
    "Adityapur	ADTP",
    "Adoni	AD	",
    "Adra Junction	ADRA	",
    "Delhi	ANDI	",
    "Aduturai	ADT	",
    "Agartala	AGTL	",
    "Agasod	AGD	",
    "Aghwanpur	AWP	",
    "Agomoni	AGMN",
    "Agori Khas	AGY	",
    "Agra	AGC	",
    "Agra	AGA	",
    "Agra	AF	",
    "Ahalyapur	AHLR	",
    "Aherwadi	AHD	",
    "Ahiran	AHN	",
    "Ahmadgarh	AHH",
    "Ahmadnagar	ANG	",
    "Ahmadpur	AMP	",
    "Ahmedabad	ADI	",
    "Ahmedabad Mg	ADIJ",
    "Ahraura Road	ARW	",
    "Aishbagh	ASH	",
    "Ait	AIT	",
    "Aithal	ATMO",
    "Ajaibpur	AJR	",
    "Ajanti	ANI	",
    "Ajaraka	AIA	",
    "Ajgain	AJ	",
    "Ajjampur	AJP	",
    "Ajmer Junction	AII	",
    "Ajni	AJNI	",
    "Ajnod	AJN	",
    "Akalkot Road	AKOR	",
    "Akaltara	AKT	",
    "Akanapet	AKE	",
    "Akathumuri	AMY	",
    "Akbarganj	AKJ	",
    "Akbarnagar	AKN	",
    "Akbarpur	ABP	",
    "Akividu	AKVD	",
    "Akkaraippatti	API	",
    "Akodia	AKD	",
    "Akola Junction	AK	",
    "Akolner	AKR	",
    "Akot	AKOT	",
    "Akshaywat R Ngr	AYRN	",
    "Akurdi	AKRD	",
    "Alai	ALJ	",
    "Alai	ALAI	",
    "Alamanda	ALM	",
    "Alamnagar	AMG	",
    "Alampur	ALMR	",
    "Alandi	ALN	",
    "Aler	ALER	",
    "Algawan	AIG	",
    "Alia Bada	ALB	",
    "Aligarh Junction	ALJN	",
    "Alipur Duar	APD	",
    "Alipur Duar Junction	APDJ	",
    "Allahabad	ALY	",
    "Allahabad	ALD	",
    "Alleppey	ALLP	",
    "Alluru Road	AXR	",
    "Almatti	LMT	",
    "Alnavar Junction	LWR	",
    "Alniya	ALNI	",
    "Aluabari Road	AUB	",
    "Aluva	AWY	",
    "Alwal	ALW	",
    "Alwar	AWR	",
    "Amagura	AGZ	",
    "Amalner	AN	",
    "Amalsad	AML	",
    "Amarda Road	ARD	",
    "Amargarh	AGR	",
    "Amarpura	APA	",
    "Amarpura Rathan	AMPR	",
    "Lucknow	AMS	",
    "Amb Andaura	AADR	",
    "Ambagaon	AGB	",
    "Ambala	UMB	",
    "Ambala	UBC	",
    "Ambalapuzha	AMPA	",
    "Ambale	ABLE	",
    "Ambari Falakata	ABFC	",
    "Ambarnath	ABH	",
    "Ambasa	ABSA	",
    "Ambasamudram	ASD	",
    "Ambaturai	ABI	",
    "Ambika Kalna	ABKA	",
    "Ambika Rohina	AMBR	",
    "Ambikapur	ABKP	",
    "Ambli Road	ABD	",
    "Ambliyasan	UMN	",
    "Ambodala	AMB	",
    "Ambur	AB	",
    "Amdara	UDR	",
    "Amethi	AME	",
    "Amgaon	AGN	",
    "Amguri	AGI	",
    "Amla Junction	AMLA	",
    "Amlai	AAL	",
    "Amlakhurd	AMX	", ,
    "Amli	AMLI	",
    "Ammanabrolu	ANB	",
    "Ammasandra	AMSA	",
    "Ammuguda	AMQ	",
    "Amoni	AONI	",
    "Amravati	AMI	",
    "Amritapura	AMC	",
    "Amritsar	ASR	",
    "Amroha	AMRO	",
    "Anakapalle	AKP	",
    "Anand	ANND	",
    "Anand Nagar	ANDN	",
    "New Delhi	ANVR	",
    "Anand Vihar Trm	ANVT	",
    "Anandapuram	ANF	",
    "Anandpur Sahib	ANSB	",
    "Anantapur	ATP	",
    "Anantnag	ANT	",
    "Anaparti	APT	",
    "Anara	ANR	",
    "Anas	ANAS	",
    "Anavardikhanpet	AVN	",
    "Ancheli	ACL	",
    "Andal Junction	UDL	",
    "Mumbai	ADH	",
    "Andul	ADL	",
    "Angadippuram	AAM	",
    "Angamali	AFK	",
    "Angar	AAG	",
    "Angul	ANGL	",
    "Anjani	ANO	",
    "Anjar	AJE	",
    "Anjhi Shahabad	AJI	",
    "Ank Mmr Direct	ANKX	",
    "Ankai	ANK	",
    "Ankleshwar	AKV	",
    "Ankola	ANKL	",
    "Ankorah Akorha	ANH	",
    "Annavaram	ANV	",
    "Annigeri	NGR	",
    "Anpara	ANPR	",
    "Antah	ATH	",
    "Antu	ANTU	",
    "Anugraha N Road	AUBR	",
    "Anuppur Junction	APR	",
    "Anupshahr	AUS	",
    "Aonla	AO	",
    "Appikatla	APL	",
    "Apta	APTA	",
    "Ara	ARA	",
    "Arag	ARAG	",
    "Arakkonam	AJJ	",
    "Arakku	ARK	",
    "Aralvaymozhi	AAY	",
    "Arand	ARN	",
    "Arang Mahanadi	ANMD	",
    "Arariya	ARR	",
    "Arariya Court	ARQ	",
    "Aravali Road	AVRD	",
    "Aravankadu	AVK	",
    "Arigada	ARGD	",
    "Ariyalur	ALU	",
    "Arjansar	AS	",
    "Arjuni	AJU	",
    "Arnetha	ARE	",
    "Arni Road	ARV	",
    "Arnia	ARNA	",
    "Arsikere	ASK	",
    "Arumuganeri	ANY	",
    "Arunachal	ARCL	",
    "Aruppukkottai	APK	",
    "Asafpur	AFR	",
    "Asalpur Jobner	JOB	",
    "Asangaon	ASO	",
    "Asansol	ASN	",
    "Asaoti	AST	",
    "Asarva Junction	ASV	",
    "Ashapura Gomat	AQG	",
    "Ashok Nagar	ASKN	",
    "Ashokapuram	AP	",
    "Ashtegaon	ASTG	",
    "Asifabad Road	ASAF	",
    "Aslana	ANA	",
    "Aslaoda	ASL	",
    "Asokhar	AXK	",
    "Asranada	AAS	",
    "Atari	ATT	",
    "Atarra	ATE	",
    "Ateli	AEL	",
    "Athmal Gola	ATL	",
    "Atrampur	ARP	",
    "Atru	ATRU	",
    "Attabira	ATS	",
    "Attar	ATR	",
    "Attili	AL	",
    "Attippattu	AIP	",
    "Attur	ATU	",
    "Atul	ATUL	",
    "Aujari	AJRE	",
    "Aulenda	AED	",
    "Aung	AUNG	",
    "Aunrihar Junction	ARJ	",
    "Aurangabad	AWB	",
    "Ausa Road	OSA	",
    "Auvaneswsarem	AVS	",
    "Auwa	AUWA	",
    "Avadi	AVD	",
"Awantipura	ATPA	",
"Awatarnagar	ATNR	",
"Ayodhya	AY	",
"Ayodhyapattanam	APN	",
"Azamgarh	AMH	",
"Azamnagar Road	AZR	",
"Azimganj City	ACLE	",
"Azimganj Junction	AZ	",
"B Cement Nagar	BEY	",
"Babatpur	BTP	",
"Babhnan	BV	",
"Babina	BAB	",
"Babrala	BBA	",
"Babugarh	BBO	",
"Babupeth	BUPH	",
"Bacheli	BCHL	",
"Bachhrawan	BCN	",
"Bachwara Junction	BCA	",
"Bad	BAD	",
"Badabandha	BDBA	",
"Badami	BDM	",
"Badampudi	BPY	",
"Badarpur Junction	BPB	",
"Badarwas	BDWS	",
"Bade Arapur	BDXX	",
"Badhal	BDHL	",
"Badhwa Bara	BDWA	",
"Badkulla	BDZ	",
"Badla Ghat	BHB	",
"Badlapur	BUD	",
"New Delhi	BHD	",
"Badmal	BUDM	",
"Badnapur	BDU	",
"Badnera Junction	BD	",
"Badodar	BDDR	",
"Badshahnagar	BNZ	",
"Badshahpur	BSE	",
"Badulipar	BLPR	",
"Badurpur Ghat	BPG	",
"Badwasi	BWS	",
"Bagaha	BUG	",
"Bagahai Road	BGHI	",
"Bagalia	BGA	",
"Bagalkot	BGK	",
"Bagbahra	BGBR	",
"Bagdihi	BEH	",
"Bagetar	BF	",
"Bagevadi Road	BSRX	",
"Baghauli	BGH	",
"Baghdogra	BORA	",
"Baghnapara	BGRA	",
"Baghora	BJQ	",
"Baghuapal	BGPL	",
"Bagnan	BZN	",
"Bagra Tawa	BGTA	",
"Bagri Nagar	BQN	",
"Bagri Sajjanpur	BGX	",
"Bagumra	BGMR	",
"Bagwada(Halt)	BAGD	",
"Bagwali	BWB	",
"Bahadur Singh W	BSS	",
"Bahadurgarh	BGZ	",
"Bahadurpur	BPD	",
"Baheri	BHI	",
"Bahjoi	BJ	",
"Bahraich	BRK	",
"Baiguda	BGUA	",
"Baihatola	BATL	",
"Baikunth	BKTH	",
"Baikunthpur Road	BRH	",
"Bainchi	BOI	",
"Bairagarh	BIH	",
"Bairagnia	BGU	",
"Baitalpur	BALR	",
"Baitarani Road	BTV	",
"Baiyyappanahali	BYPL	",
"Bajrangarh	BJG	",
"Bajud	BJUD	",
"Bajva	BJW	",
"Bakanian Bhaunr	BQE	",
"Bakhleta	BQQ	",
"Bakhtiyarpur Junction	BKP	",
"Baktal	BKTL	",
"Bakudi	BKLE	",
"Balabhadrapuram	BBPM	",
"Balabnramapuram	BRAM	",
"Balagarh	BGAE	",
"Balaghat Junction	BTC	",
"Balamu Junction	BLM	",
"Balangir	BLGR	",
"Balasore	BLS	",
"Balawali	BLW	",
"Bale	BALE	",
"Balganur	BLR	",
"Balharshah	BPQ	",
"Baliakheri	BAE	",
"Balichak	BCK	",
"Ballabgarh	BVH	",
"Ballenahalli	BAHI	",
"Ballia	BUI	",
"Bally	BLY	",
"Balod	BXA	",
"Balotra Junction	BLT	",
"Balpur Halt	BPRH	",
"Balrampur	BLP	",
"Balsamand	BLSD	",
"Balugan	BALU	",
"Balurghat	BLGT	",
"Bamanwali	BMNL	",
"Bamhrauli	BMU	",
"Bamla	BMLL	",
"Bamnia	BMI	",
"Bamra	BMB	",
"Banahi	BYN	",
"Banapura	BPF	",
"Banar	BNO	",
"Banas	BNS	",
"Banaswadi	BAND	",
"Banbasa	BNSA	",
"Banda	BNDA	",
"Bandakpur	BNU	",
"Bandanwara	BDW	",
"Bandarkhal	BXK	",
"Bandel Junction	BDC	",
"Bandh Bareta	BR	",
"Bandhua	BNF	",
"Bandikui Junction	BKI	",
"Mumbai	BDTS	",
"Bangalore	BNC	",
"Bangalore	SBC	",
"Bangalore	BNCE	",
"Bangarapet	BWY	",
"Bangarapet	BWT	",
"Bangriposi	BGY	",
"Bangrod	BOD	",
"Bani	BANI	",
"Bani Bihar	BNBH	",
"Banihal	BAHL	",
"Banisar	BS	",
"Banka	BAKA	",
"Banka Ghat	BKG	",
"Banka Road Oa	BNKR",	
"Bankata	BTK	",
"Bankhedi	BKH	",
"Bankura	BQA	",
"Banmor	BAO	",
"Bano	BANO	",
"Banpas	BPS	",
"Bansh Baria	BSAE	",
"Banshlai Bridge	BSBR	",
"Bansi Paharpur	BIQ	",
"Bansipur	BSQP	",
"Banskho	BSKO	",
"Banspani	BSPX	",
"Bansthali Niwai	BNLW	",
"Banta Rnathgarh	BGG	",
"Bantanahal	BLL	",
"Bantawala	BNTL	",
"Banthra	BTRA	",
"Baori Thikria	BOTI	",
"Bap	BAF	",
"Bapatla	BPP	",
"Bapudm Motihari	MKI	",
"Bapudm Motihari	BMKI	",
"Bar	BAR	",
"Bara Jamda	BJMD	",
"Barabambo	BRM	",
"Barabanki Junction	BBK	",
"Barabhum	BBM	",
"Barabil	BBN	",
"Barachak	BCQ	",
"Baradwar	BUA	",
"Baragopal	BAGL	",
"Barahat	BHLE	",
"Barahu	BRHU	",
"Baraigram Jn	BRGM	",
"Barakar	BRR	",
"Baral	BARL	",
"Baramati	BRMT	",
"Baran	BAZ	",
"Barang	BRAG	",
"Barara	RAA	",
"Barauni Junction	BJU	",
"Baraut	BTU	",
"Barbatpur	BBTR	",
"Barchi Road	BCRD	",
"Barddhaman Junction	BWN	",
"Bardhana Halt	BRDH	",
"Bardoli	BIY	",
"Bareilly	BRY	",
"Bareilly	BE	",
"Bareilly	BC	",
"Barejadi	BJD	",
"Barelipur	BQM	",
"Bareta	BRZ	",
"Bareth	BET	",
"Bargarh	BRG	",
"Bargarh Road	BRGA	",
"Bargawan	BRGW	",
"Bargi	BUQ	",
"Barh	BARH	",
"Barhan	BRN	",
"Barharwa Junction	BHW	",
"Barhiya	BRYA	",
"Barhiya	DKGS	",
"Barhni	BNY	",
"Bari Brahman	BBMN	",
"Bariarpur	BUP	",
"Baripada	BPO	",
"Bariwala	BRW	",
"Barka Kana	BRKA	",
"Barkhera	BKA	",
"Barkisalalya	BSYA	",
"Barkur	BKJ	",
"Barlai	BLAX	",
"Barmer	BME	",
"Barnala	BNN	",
"Barog	BOF	",
"Barpali	BRPL	",
"Barpathar	BXP	",
"Barpeta Road	BPRD	",
"Barrackpore	BP	",
"Barrajpur	BJR	",
"Barsali	BYS	",
"Barsi Town	BTW	",
"Barsoi Junction	BOE	",
"Barsola	BZO	",
"Barua Bamungaon	BBGN	",
"Barud	BRUD	",
"Barwa Sagar	BWR	",
"Barwadih Junction	BRWD	",
"Barwaha	BWW	",
"Barwala	BXC	",
"Barya Ram	BYHA	",
"Basai	BZY	",
"Basampalle	BSPL	",
"Basantapur	BSTP	",
"Basar	BSX	",
"Basbari	BSI	",
"Basharatganj	BTG	",
"Basin Bridge Junction	BBQ	",
"Basmat	BMF	",
"Basni	BANE	",
"Bassi	BAI	",
"Bassi Pathanam	BSPN	",
"Basta	BTS	",
"Basti	BST	",
"Basugaon	BSGN	",
"Basukinath	BSKH	",
"Baswa	BU	",
"Batala Junction	BAT	",
"Bataspur	BSLE	",
"Bathinda Cantt.BTIC	",
"Bauria Junction	BVA	",
"Bawal	BWL	",
"Bawani Khera	BWK	",
"Bayana	BXN	",
"Baytu	BUT	",
"Bayyavaram	BVM	",
"Bazarsau	BZLE	",
"Bazpur	BPZ	",
"Beas	BEAS	",
"Beawar	BER	",
"Bechhiwara	BHWA	",
"Hyderabad	BMT	",
"Begdewadi	BGW	",
"Begu Sarai	BGS	",
"Behtagokul	BEG	",
"Behula	BHLA	",
"Bekal Fort	BFR	",
"Bela	BELA	",
"Bela Tal	BTX	",
"Belakoba	BLK	",
"Belampalli	BPA	",
"Belapur	BAP	",
"Belasar	BLSR	",
"Belda	BLDA	",
"Beldanga	BEB	",
"Belgahna	BIG	",
"Belgaum	BGM	",
"Belgharia	BLH	",
"Belha	BYL	",
"Bellamkonda	BMKD	",
"Bellary Cant	BYC	",
"Bellary	BAY	",
"Bellenahalli	BNHL	",
"Belpahar	BPH	",
"Belrayan	BXM	",
"Belsonda	BLSN	",
"Belthara Road	BLTR	",
"Belvandi	BWD	",
"Beohari	BEHR	",
"Berawanya	BRNA	",
"Berchha	BCH	",
"Berhampore Crt	BPC	",
"Bermo	BRMO	",
"Besroli	BSRL	",
"Betamcherla	BMH	",
"Betavad	BEW	",
"Bethampurdi	BTPD	",
"Bethuadahari	BTY	",
"Betnoti	BTQ	",
"Bettiah	BTH	",
"Betul	BZU	",
"Bevinahalu	BNL	",
"Bhabhar	BAH	",
"Bhabta	BFT	",
"Bhabua Road	BBU	",
"Bhachau	BCO	",
"Bhachau Bg	BCOB	",
"Bhadan	BDN	",
"Bhadanpur	BUU	",
"Bhadaura	BWH	",
"Bhadbhadaghat	BVB	",
"Bhadbhunja	BBAI	",
"Bhadli	BDI	",
"Bhadohi	BOY	",
"Bhadrachalam Road	BDCR	",
"Bhadrakh	BHC	",
"Bhadravati	BDVT	",
"Bhadreshwar	BHR	",
"Bhadri	BHDR	",
"Bhadroli	BBY	",
"Bhaga Junction	VAA	",
"Bhagalpur	BGP	",
"Bhagalpur	ZZZZ	",
"Bhagat Ki Kothi	BGKT	",
"Bhagwangola	BQG	",
"Bhagwanpur	BNR	",
"Bhagwanpura	BGPR	",
"Bhairoganj	BRU	",
"Bhairongarh	BOG	",
"Bhakti Nagar	BKNG	",
"Bhalki	BHLK	",
"Bhalui	BFM	",
"Bhaluka Road F	BKRD	",
"Bhalukmara	BLMR	",
"Bhalulata	BUL	",
"Bhalumaska	BLMK	",
"Bhalwani	BLNI	",
"Bhan Kari	BAK	",
"Bhanapur	BNP	",
"Bhandak	BUX	",
"Bhandara Road	BRD	",
"Bhandaridah	BHME	",
"Bhandu Motidau	BHU	",
"Bhansi	BHNS	",
"Bhanvad	BNVD	",
"Bhanvad	BNUD	",
"Bhanwar Tonk	BHTK	",
"Bhanwasa	BNWS	",
"Bharat Kup	BTKP	",
"Bharatpur Junction	BTE	",
"Bharoli	BHRL	",
"Bharthana	BNT	",
"Bharuch	BH	",
"Bharwa Sumerpur	BSZ	",
"Bharwari	BRE	",
"Bhatapara	BYT	",
"Bhatinda Junction	BTI	",
"Bhatisuda(Halt)	BTSD	",
"Bhatiya	BHTA	",
"Bhatkal	BTKL	",
"Bhatkal	BTJL	",
"Bhatni Junction	BTT	",
"Bhaton Ki Gali	BHG	",
"Bhatpar Rani	BHTR	",
"Bhattiprolu	BQU	",
"Bhattu	BHT	",
"Bhavanagar Para	BVP	",
"Bhavani Nagar	BVNR	",
"Bhavnagar Trmus	BVC	",
"Bhawani Mandi	BWM	",
"Bhawanipatna	BWIP	",
"Bhayandar	BYR	",
"Bhayavadar	BHY	",
"Bhedia	BDH	",
"Bheerpur	BEP	",
"Bheja	BHJA	",
"Bheraghat	BRGT	",
"Bhesana	BFY	",
"Bheslana	BILA	",
"Bhestan	BHET	",
"Bhigwan	BGVN	",
"Bhiknur	BKU	",
"Bhilad	BLD	",
"Bhilai	BIA	",
"Bhilai Pwr Hs	BPHB	",
"Bhilainagar	BQR	",
"Bhilavdi	BVQ	",
"Bhildi	BLDI	",
"Bhilwara	BHL	",
"Bhimadolu	BMD	",
"Bhimal	BIML	",
"Bhimalgondi	BMC	",
"Bhimana	BMN	",
"Bhimasar Bg	BMSB	",
"Bhimavaram Junction	BVRM	",
"Bhimavaram Town	BVRT	",
"Bhimgara	BMGA	",
"Bhimkhoj	BMKJ	",
"Bhimsen	BZM	",
"Bhind	BIX	",
"Bhinwaliya	BWA	",
"Bhira Kheri	BIK	",
"Bhitaura	BTO	",
"Bhitoni	BHTN	",
"Bhivpuri Road	BVS	",
"Bhiwandi Road	BIRD	",
"Bhiwani	BNW	",
"Bhiwani City	BNWC	",
"Bhogpur	BPRS	",
"Bhojipura Junction	BPR	",
"Bhojo	BOJ	",
"Bhojudih Junction	BJE	",
"Bhokar	BOKR	",
"Bhoke	BOKE	",
"Bhoma	BHV	",
"Bhone	BHNE	",
"Bhongaon	BGQ	",
"Bhongir	BG	",
"Bh Onra	BON	",
"Bhopal Junction	BPL	",
"Bhoras Budrukh	BFJ	",
"Bhortex	BRTK	",
"Bhubaneswar	BBS	",
"Bhuchchu	BCU	",
"Bhugaon	BPK	",
"Bhuj	BHUJ	",
"Bhulanpur	BHLP	",
"Bhulon	BLO	",
"Bhupalsagar	BSJ	",
"Bhupdeopur	BEF	",
"Bhupia Mau	VPO	",
"Bhurkunda	BHKD	",
"Bhusandpur	BSDP	",
"Bhusaval Junction	BSL	",
"Bhuteshwar	BTSR	",
"Bibinagar	BN	",
"Bichia	BIC	",
"Bidadi	BID	",
"Bidanpur	BDNP	",
"Bidar	BIDR	",
"Bidhan Nagar	BNXR	",
"Bidupur	BIU	",
"Bigga	BIGA	",
"Bighapur	BQP	",
"Bihar Sharif	BEHS	",
"Bihara	BHZ	",
"Bihiya	BEA	",
"Bihta	BTA	",
"Bijainagar	BJNR	",
"Bijapur	BJP	",
"Bijauli	BJI	",
"Bijaysota	VST	",
"Bijni	BJF	",
"Bijnor	BJO	",
"Bijoor	BIJR	",
"Bijora	BJK	",
"Bijuli Halt	BJIH	",
"Bijuri	BJRI	",
"Bijwasan	BWSN	",
"Bikaner Junction	BKN	",
"Bikkavolu	BVL	",
"Bikram Shila	BKSL	",
"Bikrampur	BMR	",
"Bilaspur Junction	BSP	",
"Bilaspur Road	BLQR	",
"Bilaspur Road	BLOR	",
"Bildi	BILD	",
"Bilga	BZG	",
"Bilhar Ghat	BLG	",
"Bilhaur	BLU	",
"Bilimora	BIM	",
"Billi	BXLL	",
"Bilpur	BLPU	",
"Bilwai	BWI	",
"Bina Junction	BINA	",
"Binaiki	VNK	",
"Bindayaka	BDYK	",
"Bindki Road	BKO	",
"Binnaguri	BNV	",
"Bir	BIR	",
"Biradhwal	BDWL	",
"Birambad	BAMA	",
"Biramdih	BRMD	",
"Birang Khera	BMK	",
"Birapatti	BRPT	",
"Birlanagar	BLNR	",
"Birnagar	BIJ	",
"Birohe	BEO	",
"Biroliya	BRLY	",
"Birsinghpur	BRS	",
"Birur	RRB	",
"Bisalwas Kalan	BIWK	",
"Bisanattam	BSM	",
"Bisapurkalan	BRKH	",
"Bishnathganj	BTJ	",
"Bishnupur	VSU	",
"Bishrampur	BSPR	",
"Bisra	BZR	",
"Bissamcuttack	BMCK	",
"Bissau	BUB	",
"Bisugirsharif	BGSF	",
"Biswan	BVN	",
"Bitragunta	BTTR	",
"Biyavra Rajgarh	BRRG	",
"Bobas	BOBS	",
"Bobbili	VBL	",
"Bodhadi Bujrug	BHBK	",
"Bodwad	BDWD	",
"Bohali	BHLI	",
"Bohani	BNE	",
"Boinda	BONA	",
"Boisar	BOR	",
"Bokajan	BXJ	",
"Bokaro	BKSC	",
"Bokaro Thermal	BKRO	",
"Bolai	BLX	",
"Bolarum	BMO	",
"Bolarum Bazar	BOZ	",
"Bolinna Doaba	BLND	",
"Bolpur S Niktn	BHP	",
"Bolsa	BLSA	",
"Bomadra	BOM	",
"Bommidi	BQI	",
"Bona Kalu	BKL	",
"Bondamunda	BNDM	",
"Bongaigaon	BNGN	",
"Bonidanga	BDAG	",
"Borawar	BOW	",
"Bordhal	BXY	",
"Bordi	BIO	",
"Borhat	BFD	",
"Boribial	BRB	",
"Boridand	BRND	",
"Mumbai	BVI	",
"Boroti	BOT	",
"Borraguhallu	BGHU	",
"Bortalao	BTL	",
"Borvihir	BRVR	",
"Botad Junction	BTD	",
"Bpt Station	XXXX	",
"Brahmanagudem	BMGM	",
"Brahmanpalli	BMPL	",
"Brahmapur	BAM	",
"Brajrajnagar	BRJN	",
"Brayla Chaurasi	BRLA	",
"Budalur	BAL	",
"Budaun	BEM	",
"Buddireddippati	BDY	",
"Budhi	BDHY	",
"Budhlada	BLZ	",
"Budni	BNI	",
"Budvel	BDVL	",
"Bulandshahr	BSC	",
"Bundi	BUDI	",
"Bundki	BEK	",
"Buniadpur	BNDP	",
"Burhanpur	BAU	",
"Burhar	BUH	",
"Burhwal	BUW	",
"Burnpur	BURN	",
"Butari	BTR	",
"Buti Bori	BTBR	",
"Buxar	BXR	",
"Byadarahalli	BDRL	",
"Byadgi	BYD	",
"Byculla	BY	",
"Byndoor	BYNR	",
"Kolhapur	KOP	",
"Cancona	CNO	",
"Castle Rock	CLR	",
"Cavalry Barrcks	CVB	",
"Chabua	CHB	",
"Chachaura Bngj	CBK	",
"Chacher	CHCR	",
"Chagallu	CU	",
"Chaibasa	CBSA	",
"Chainpur	CNPR	",
"Chainwa	CW	",
"Chajawa	CJW	",
"Chajli	CJL	",
"Chakand	CKH	",
"Chakarbhatha	CHBT	",
"Chakarlapalli	CPL	",
"Chakarpur	CKK	",
"Chakdaha	CDH	",
"Chakdayala	CKDL	",
"Chakia	CAA	",
"Chakki Bank	CHKB	",
"Chakradharpur	CKP	",
"Chakraj Mal	CAJ	",
"Chakrod	CKOD	",
"Chaksu	CKS	",
"Chakulia	CKU	",
"Chakur	CKX	",
"Chalakudi	CKI	",
"Chalama	CMZ	",
"Chalgeri	CLI	",
"Chalisgaon	CSN	",
"Challakere	CHKE	",
"Chalsa Junction	CLD	",
"Chalthan	CHM	",
"Chamagram	CMX	",
"Chamarajanagar	CMNR	",
"Champa	CPH	",
"Champaner Road Jn	CPN	",
"Chand Siau	CPS	",
"Chanda Fort	CAF	",
"Chandan Nagar	CGR	",
"Chandanattop	CTPE	",
"Chandari	CNBI	",
"Chandauli Mjhwr	CDMR	",
"Chandausi	CH	",
"Chandawal	CNL	",
"Chanderiya	CNA	",
"Chandi Mandir	CNDM	",
"Chandia Road	CHD	",
"Chandigarh	CDG	",
"Chandil Junction	CNI	",
"Chandlodiya	CDLD	",
"Chandlodiya	CLDY	",
"Chandok	CNK	",
"Chandragiri	CGI	",
"Chandrakona Road	CDGR	",
"Chandranathpur	CNE	",
"Chandrapur	CD	",
"Chandrapura	CRP	",
"Chandur	CND	",
"Chandur Bazar	CNDB	",
"Chaneti	CHTI	",
"Changanaseri	CGY	",
"Changotola	CGLA	",
"Changsari	CGS	",
"Channani	CHNN	",
"Channapatna	CPT	",
"Chanpatia	CAI	",
"Chaparmukh Junction	CPK	",
"Charamula Kusum	CJS	",
"Charanmahadevi	SMD	",
"Charaud	CRW	",
"Charbatia	CBT	",
"Charegaon	CRN	",
"Charghat Pipari	CGE	",
"Charkhera	CRK	",
"Dadri	CKD	",
"Charlapalli	CHZ	",
"Charvattur	CHV	",
"Chata	CHJ	",
"Chatra	CTR	",
"Chatrappatti	CHPT	",
"Chatrapur	CAP	",
"Chattriput	CTS	",
"Chau Mahla	CMU	",
"Chaube	CBH	",
"Chauk	CHOK	",
"Chaukhandi	CHH	",
"Chaunrah	CNH	",
"Chaura	CUX	",
"Chauri Chaura	CC	",
"Chausa	CSA	",
"Chautara	CROA	",
"Chauth Ka Brwra	CKB	",
"Chavaj	CVJ	",
"Chavalkhede	CHLK	",
"Chawapall	CHA	",
"Chebrol	CEL	",
"Cheekateegalplm	CEM	",
"Chengalpattu	CGL	",
"Chengannur	CNGR	",
"Chennai	MSB	",
"Chennai	MAS	",
"Chennai	MS	",
"Chennasandra	CSDR	",
"Cheoki	COI	",
"Cheriyanad	CYN	",
"Cherukara	CQA	",
"Chettinad	CTND	",
"Chhabra Gugor	CAG	",
"Chhan Arorian	CHNR	",
"Chhandrauli	CDRL	",
"Chhanera	CAER	",
"Chhapi	CHP	",
"Chhapra	CPR	",
"Chhapra Kacheri	CI	",
"Chharodi	CE	",
"Chharra	CHRA	",
"Chhatna	CJN	",
"Chhina	CHN	",
"Chhindwara Junction	CWA	",
"Chhipadohar	CPDR	",
"Chhota Gudha	COD	",
"Chhoti Odai	COO	",
"Chhulha	CLF	",
"Chichaki	CCK	",
"Chidambaram	CDM	",
"Chigicherla	CCA	",
"Chiheru	CEU	",
"Chik Banavar	BAW	",
"Chikalthan	CTH	",
"Chikhli	CKHS	",
"Chikjajur Junction	JRU	",
"Chikni Road	CKNI	",
"Chikodi Road	CKR	",
"Chilakalapudi	CLU	",
"Chilbila Junction	CIL	",
"Chilikidara	CLDR	",
"Chilka	CLKA	",
"Chilkahar	CHR	",
"Chilo	CLO	",
"Chiluvur	CLVR	",
"Chima Pahad	CMW	",
"Chimidipalli	CMDP	",
"Chinchli	CNC	",
"Chinchpada	CPD	",
"Pune	CCH	",
"Chinna Ganjam	CJM	",
"Chinna Salem	CHSM	",
"Chinnaravuru	CIV	",
"Chinpai	CPLE	",
"Chintaman Ganes	CNN	",
"Chiplun	CHI	",
"Chipurupalle	CPP	",
"Chirala	CLX	",
"Chirawa	CRWA	",
"Chirayinkil	CRY	",
"Chirgaon	CGN	",
"Chirmiri	CHRM	",
"Chit Baragaon	CBN	",
"Chitahra	CTHR	",
"Chitali	CIT	",
"Chitgidda	CTF	",
"Chitradurg	CTA	",
"Chitrakot	CKTD	",
"Chitrasani	CTT	",
"Chitrod	COE	",
"Chittapur	CT	",
"Chittaranjan	CRJ	",
"Chittaurgarh	COR	",
"Chittor	CTO	",
"Chityala	CTYL	",
"Chodiala	CDL	",
"Chola	CHL	",
"Chomun Samod	COM	",
"Chopan	CPU	",
"Choral	CRL	",
"Chorghatpiparia	CRE	",
"Chorgi	CHRG	",
"Chorvad Road	CVR	",
"Choti Khatu	CTKT	",
"Choupale	CUE	",
"Chuchura	CNS	",
"Chudawa	CRU	",
"Chunar	CAR	",
"Churaibari	CBZ	",
"Churk	CUK	",
"Churu	CUR	",
"Cinnamara	CMA	",
"Clutterbuckganj	CBJ	",
"Coimbatore	CBE	",
"Coimbatore	CBF	",
"Colonelganj	CLJ	",
"Contai Road	CNT	",
"Coonoor	ONR	",
"Cossimbazar	CSZ	",
"Cuddalore Port	CUPJ	",
"Cuddapah	HX	",
"Cumbum	CBM	",
"Cuttack	CTC	",
"Dabhaura	DBR	",
"Dabhoda	DBO	",
"Dabilpur	DBV	",
"Dabka	DBKA	",
"Dabla	DBLA	",
"Dabli Rathan	DBI	",
"Dabpal	DPF	",
"Dabpal	DBF	",
"Dabra	DBA	",
"Dabtara	DUB	",
"Mumbai	DR	",
"Mumbai	DDR	",
"Dadhapara	DPH	",
"Dadhdevi	DDV	",
"Dadpur	DPX	",
"Dadri	DER	",
"Dagarhkeri	DRHI	",
"Daghora	DAO	",
"Dagmagpur	DAP	",
"Dagori	DGS	",
"Mumbai	DRD	",
"Dahar Ka Balaji	DKBJ	",
"Dahod	DHD	",
"Dakaniya Talav	DKNT	",
"Dakhineswar	DAKE	",
"Daladi	DL	",
"Dalauda	DLD	",
"Dalbhumgarh	DVM	",
"Dalelnagar	DLQ	",
"Dalgaon	DLO	",
"Daliganj	DAL	",
"Dalkolha	DLK	",
"Dalli Rajhara	DRZ	",
"Dalmau Junction	DMW	",
"Dalmera	DLC	",
"Dalpatpur	DLP	",
"Dalsingh Sarai	DSS	",
"Daltonganj	DTO	",
"Damanjodi	DMNJ	",
"Damchara	DCA	",
"Damoh	DMO	",
"Danapur	DNR	",
"Danauli Phlwria	DPL	",
"Dandupur	DND	",
"Danea	DNEA	",
"Dangarwa	DNW	",
"Dangoaposi	DPS	",
"Danishpet	DSPT	",
"Daniyawan Bzr H	DNWH	",
"Dankaur	DKDE	",
"Dankuni	DKAE	",
"Dantan	DNT	",
"Dantewara	DWZ	",
"Dantra	DTRA	",
"Danwar	DAR	",
"Daotuhaja	DJA	",
"Dapodi	DAPD	",
"Dappar	DHPR	",
"Dara	DARA	",
"Darbhanga Junction	DBG	",
"Darekasa	DKS	",
"Darjeeling	DJ	",
"Darliput	DPC	",
"Darritola	DTL	",
"Daryabad	DYD	",
"Dasharathpur	DRTP	",
"Dasna	DS	",
"Dasuya	DZA	",
"Datia	DAA	",
"Daudpur	DDP	",
"Daulatabad	DLB	",
"Daulatpur Hat	DLPH	",
"Daund Junction	DD	",
"Daurai	DOZ	",
"Daurala	DRLA	",
"Dauram Madhpura	DMH	",
"Dausa	DO	",
"Dausni	DSNI	",
"Davangere	DVG	",
"Dayalpur	DLPR	",
"Dayanand Nagar	DYE	",
"Debagram	DEB	",
"Debari	DRB	",
"Deeg	DEEG	",
"Degana Junction	DNA	",
"Dehradun	DDN	",
"Dehri On Sone	DOS	",
"Dehu Road	DEHR	",
"Dekargaon	DKGN	",
"Delang	DEG	",
"New Delhi	DLI	",
"New Delhi	DEC	",
"New Delhi	DKZ	",
"New Delhi	DEE	",
"New Delhi	DSJ	",
"New Delhi	DSA	",
"Denduluru	DEL	",
"Deoband	DBD	",
"Deoghar	DGHR	",
"Deojhar	DJHR	",
"Deori	DOE	",
"Deoria Sadar	DEOS	",
"Deotala	DOTL	",
"Depur Ph	DPUR	",
"Derol	DRL	",
"Derowan P.H.DRWN	",
"Desari	DES	",
"Deshapran P.H.DSPN	",
"Deshnok	DSO	",
"Deswal	DSL	",
"Devakottai Road	DKO	",
"Devalgaon Auchr	DAV	",
"Devangonthi	DKN	",
"Devarapalli	DPE	",
"Devargudda	DAD	",
"Devbaloda Chrda	DBEC	",
"Devi Halt	DVH	",
"Devlali	DVL	",
"Devpura	DPZ	",
"Devri Ph	DRPH	",
"Dewanganj	DWG	",
"Dewas	DWX	",
"Dhaban	DABN	",
"Dhaca Cantt	DHCA	",
"Dhaka	DAKA	",
"Dhalgaon	DLGN	",
"Dhalpukhuri	DHRY	",
"Dhamalgaon	DMGN	",
"Dhamangaon	DMN	",
"Dhamara Ghat	DHT	",
"Dhamdhamia	DDX	",
"Dhamora	DAM	",
"Dhampur	DPR	",
"Dhana Kherli	DXK	",
"Dhanakya	DNK	",
"Dhanapur Orissa	DIR	",
"Dhanari	DN	",
"Dhanauri	DNRE	",
"Dhanbad	DHN	",
"Dhandari Kalan	DDL	",
"Dhandhera	DNRA	",
"Dhanera	DQN	",
"Dhaneta	DAN	",
"Dhanmandal	DNM	",
"Dhansu	DNX	",
"Dhanuvachapuram	DAVM	",
"Dhapewara	DPW	",
"Dharamtul	DML	",
"Dharangaon	DXG	",
"Dhareshwar	DRS	",
"Dharewada	DRW	",
"Dharhara	DRH	",
"Dhariwal	DHW	",
"Dharmabad	DAB	",
"Dharmanagar	DMR	",
"Dharmapuri	DPJ	",
"Dharmavaram Junction	DMM	",
"Dharmpur Hmchl	DMP	",
"Dharnaoda	DHR	",
"Dharuadihi	DIH	",
"Dharur	DRR	",
"Dharwar	DWR	",
"Dhasa Junction	DAS	",
"Dhatrigram	DTAE	",
"Dhaulpur	DHO	",
"Dhauni	DWLE	",
"Dhaura	DUA	",
"Dhavalas	DHS	",
"Dheena	DHA	",
"Dhekiajili Road	DKJR	",
"Dhekvad	DWD	",
"Dhemaji	DMC	",
"Dhengli Pp Goan	DGPP	",
"Dhenkanal	DNKL	",
"Dhigawara	DGW	",
"Dhilwan	DIW	",
"Dhinda	DHND	",
"Dhirera	DHRR	",
"Dhodhar	DOD	",
"Dhodra Mohar	DOH	",
"Dhoki	DKY	",
"Dhola Junction	DLJ	",
"Dholi	DOL	",
"Dholipal	DPK	",
"Dhondi	DNDI	",
"Dhone	DNC	",
"Dhone	DHNE	",
"Dhoraji	DJI	",
"Dhrangdhra	DHG	",
"Dhuankheri	DKRA	",
"Dhubri	DBB	",
"Dhubulia	DHU	",
"Dhule	DHI	",
"Dhulghat	DGT	",
"Dhulian Ganga	DGLE	",
"Dhulkot	DKT	",
"Dhupguri	DQG	",
"Dhuri Junction	DUI	",
"Dhurwasin	DRSN	",
"Dhutra	DTV	",
"Dibolong	DBLG	",
"Dibrugarh	DBRG	",
"Dibrugarh	DBRT	",
"Didwana	DIA	",
"Digaru	DGU	",
"Digboi	DBY	",
"Digha Flag Stn	DGHA	",
"Dighwara	DGA	",
"Digod	DXD	",
"Diguvametta	DMT	",
"Dihakho	DKE	",
"Dijaobra	DJB	",
"Dilawarnagar	DIL	",
"Dildarnagar Junction	DLN	",
"Dilmili	DMK	",
"Dilwa	DLW	",
"Dimapur	DMV	",
"Dina Nagar	DNN	",
"Dindigul Junction	DG	",
"Diphu	DPU	",
"Diplana	DPLN	",
"Disa	DISA	",
"Ditokcherra	DTC	",
"Diva	DIVA	",
"Divine Nagar	DINR	",
"Diwankhavati	DWV	",
"Diyatara Road	DTRD	",
"Diyodar	DEOR	",
"Dodballapur	DBU	",
"Dodbele	DBL	",
"Dodhi	DHE	",
"Doikallu	DKLU	",
"Doiwala	DWO	",
"Dokwa	DKWA	",
"Domingarh	DMG	",
"Donakonda	DKD	",
"Dondaicha	DDE	",
"Dongargarh	DGG	",
"Donkinavalasa	DNV	",
"Doraha	DOA	",
"Dornakal Junction	DKJ	",
"Dosvada	DSD	",
"Dubaha	DUBH	",
"Dubrajpur	DUJ	",
"Duddhinagar	DXN	",
"Dudhani	DUD	",
"Dudhwakhara	DKX	",
"Duganpur	DUN	",
"Duggirala	DIG	",
"Duliajan	DJG	",
"Dullahapur	DLR	",
"Dulrasar	DUS	",
"Dum Dum	DDJ	",
"Dumariya	DY	",
"Dumka	DUMK	",
"Dumraon	DURE	",
"Dumri Bihar	DMBR	",
"Dumri Halt	DMRX	",
"Dumri Juara	DRI	",
"Dumurdaha	DMLE	",
"Dumuriput	DMRT	",
"Dundi	DDCE	",
"Dundlod Mkdgrh	DOB	",
"Dungarpur	DNRP	",
"Dungri	DGI	",
"Dungripali	DJX	",
"Duraundha Junction	DDA	",
"Durg	DURG	",
"Durgada Gate	DGDG	",
"Durgapur	DGR	",
"Durgapura	DPA	",
"Durgauti	DGO	",
"Duroji	DAJ	",
"Dusi	DUSI	",
"Duvvada	DVD	",
"Dwarapudi	DWP	",
"Dwarka	DWK	",
"Edavai	EVA	",
"Edduladoddi	EDD	",
"Ekambarakuppam	EKM	",
"Ekangarsarai	EKR	",
"Ekchari	EKC	",
"Eklakhi	EKI	",
"Ekma	EM	",
"Ekma	EKMA	",
"Elimala	ELM	",
"Ellamanchili	YLM	",
"Ellenabad	ENB	",
"Eluru	EE	",
"Kochi	ERS	",
"Eraniel	ERL	",
"Kochi	ERN	",
"Erode Junction	ED	",
"Errupalem	YP	",
"Etawah	ETW	",
"Etmadpur	ETUE	",
"Ettapur Road	ETP	",
"Ettumanur	ETM	",
"Ezhukone	EKN	",
"Faizabad Junction	FD	",
"Faizullapur	FYZ	",
"Fakhrabad	FKB	",
"Fakiragram Junction	FKM	",
"Falakata	FLK	",
"Falna	FA	",
"Farah Town	FHT	",
"Faridabad	FDB	",
"Faridabad Nw Tn	FDN	",
"Faridkot	FDK	",
"Farrukhabad	FBD	",
"Fateh Singhpura	FSP	",
"Fatehabad Ch.Jn	FTD	",
"Fatehgarh	FGR	",
"Fatehgarh Sahib	FGSB	",
"Fatehnagar	FAN	",
"Fatehpur	FTP	",
"Fatehpur Sikri	FTS	",
"Fatehpur Skhwti	FPS	",
"Fatwa	FUT	",
"Fazalpur	FZL	",
"Fazilka	FKA	",
"Ferok	FK	",
"Firozabad	FZD	",
"Firozpur Cant	FZR	",
"Firozpur City	FZP	",
"Forbesganj	FBG	",
"Furkating Junction	FKG	",
"Fursatganj	FTG	",
"G Pochampalli	GDPL	",
"G.Ramachandrapu	GRCP	",
"Gachhipura	GCH	",
"Gadadharpur	GHLE	",
"Gadag Junction	GDG	",
"Gadarwara	GAR	",
"Gadhwala	GDW	",
"Gadiganuru	GNR	",
"Gadwal	GWD	",
"Gahlota	GLTA	",
"Gahmar	GMR	",
"Gaipura	GAE	",
"Gajapatinagaram	GPI	",
"Gajjelakonda	GJJ	",
"Gajner	GJN	",
"Gajraula	GJL	",
"Gajsinghpur	GJS	",
"Galgalia	GAGA	",
"Galudih	GUD	",
"Gambhiri Road	GRF	",
"Gamharia	GMH	",
"Ganagapur Road	GUR	",
"Ganaur	GNU	",
"Gandhidham Bg	GIMB	",
"Gandhidham Junction.GIM	",
"Gandhinagar Cap	GNC	",
"Gandhinagar Jpr	GADJ	",
"Gandhipuram Hal	GHPU	",
"Gandhismriti	GNST	",
"Ganeshganj	GAJ	",
"Gangadhara	GGAR	",
"Gangadharpur	GNGD	",
"Gangaganj	GANG	",
"Gangaghat	GAG	",
"Gangajhari	GJ	",
"Gangakher	GNH	",
"Gangani	GNNA	",
"Gangapur City	GGC",
"Gangarampur	GRMP	",
"Gangiwara	GNW	",
"Gangrar	GGR	",
"Gangsar Jaitu	GJUT	",
"Ganj Basoda	BAQ	",
"Ganj Dundwara	GWA	",
"Ganjam	GAM	",
"Gankar	GALE	",
"Gannavaram	GWM	",
"Garh Dhrubeswar	GRB	",
"Garh Jaipur	GUG	",
"Garhara	GHX	",
"Garhbeta	GBA	",
"Garhi Harsaru	GHH	",
"Garhi Manikpur	GRMR	",
"Garhmuktesar	GMS	",
"Garhmuktesar Br	GGB	",
"Garhwa	GHQ	",
"Garifa	GFAE	",
"Garividi	GVI	",
"Garla	GLA	",
"Garladinne	GDE	",
"Garot	GOH	",
"Garpos	GPH	",
"Garudubilli	GRBL	",
"Garwa Road	GHD	",
"Gatora	GTW	",
"Gaura	GRX	",
"Gauri Bazar	GB	",
"Gauribidanur	GBD	",
"Gauriganj	GNG	",
"Gauripur	GUP	",
"Gaushala	GWS	",
"Gautamdhara	GATD	",
"Gautamsthan	GTST	",
"Gaya Junction	GAYA	",
"Gayabari	GBE	",
"Gazole	GZO	",
"Gazulapalli	GZL	",
"Gede	GEDE	",
"Gegal Akhri	GEK	",
"Geratpur	GER	",
"Getor Jagatpura	GTJT	",
"Gevra Road	GAD	",
"Ghadela	GELA	",
"Ghagghar	GHG	",
"Ghagwal	GHGL	",
"Ghanauli	GANL	",
"Ghanpur	GNP	",
"Ghantikhal Ndpr	GHNH	",
"Gharaunda	GRA	",
"Ghaso	GSO	",
"Ghat Nandur	GTU	",
"Ghataka Varana	GKB	",
"Ghatampur	GTM	",
"Ghatera	GEA	",
"Ghatkesar	GT	",
"Ghatprabha	GPB	",
"Ghatsila	GTS	",
"Ghaziabad	GZB	",
"Ghazipur City	GCT	",
"Ghoga	GGA	",
"Ghoksadanga	GDX	",
"Gholvad	GVD	",
"Ghonsor	GNS	",
"Ghoradongri	GDYA	",
"Ghorawadi	GRWD	",
"Ghorpuri	GPR	",
"Ghosunda	GSD	",
"Ghughuli	GH	",
"Ghum	GHUM	",
"Ghunghuti	GGT	",
"Ghutku	GTK	",
"Gidam	GIZ	",
"Giddalur	GID	",
"Giddarbaha	GDB	",
"Gidhaur	GHR	",
"Gidni	GII	",
"Gill	GILL	",
"Ginigera	GIN	",
"Giridih	GRD	",
"Girimaidan	GMDN	",
"Girwar	GW	",
"Goaldih	GADH	",
"Goalpara Town	GLPT	",
"Godamgura	GDQ	",
"Godavari	GVN	",
"Godhra	GDA	",
"Gogameri	GAMI	",
"Gogamukh	PDKN	",
"Gogamukh	GOM	",
"Gohad Road	GOA	",
"Gohana	GHNA	",
"Gohpur	GPZ	",
"Goilkera	GOL	",
"Gokak Road	GKK	",
"Gokarna Road	GOK	",
"Gokulpur	GKL	",
"Gola Gokaranath	GK	",
"Gola Road	GRE	",
"Golaghat	GLGT	",
"Golakganj Jn	GKJ	",
"Golana Halt	GLNA	",
"Goldinganj	GJH	",
"Goldingganj	GALG	",
"Gollaprolu	GLP	",
"Golsar	GOZ	",
"Lucknow	GTNR	",
"Gomoh Junction	GMO	",
"Gomta	GTT	",
"Gonda	GD	",
"Gondal	GDL	",
"Gondia Junction	G	",
"Gondwanavisapur	GNVR	",
"Goneana	GNA	",
"Gooty	GY	",
"Gop Jam	GOP	",
"Gopalapatnam	GPT	",
"Gora Ghuma	GGM	",
"Gorakhnath	GRKN	",
"Gorakhpur	GKC	",
"Gorakhpur	GKY	",
"Gorakhpur	GKP	",
"Gorapur	GPJ	",
"Goraul	GRL	",
"Goraya	GRY	",
"Goregaon Road	GNO	",
"Goresuar	GVR	",
"Goriyan	GIO	",
"Gosalpur	GSPR	",
"Goshainganj	GGJ	",
"Gossaigaon Hat	GOGH	",
"Gotan	GOTN	",
"Gothaj	GTE	",
"Gothangam	GTX	",
"Gotlam	GTLM	",
"Gour Malda	GZM	",
"Goverdhan	GDO	",
"Govindgarh	GVG	",
"Govindgarh Malk	GND	",
"Govindi Marwar	GVMR	",
"Govindpur Road	GBX	",
"Govindpuri	GOV	",
"Govindpuri	GOY	",
"Gowdavalli	GWV	",
"Gubbi	GBB	",
"Gudaparti	GDPT	",
"Gudgeri	GDI	",
"Gudha	GA	",
"Gudimetta	GMA	",
"Gudivada Junction	GDV	",
"Gudiyattam	GYM	",
"Gudlavalleru	GVL	",
"Gudma	GDM	",
"Gudru Halt	GDU	",
"Gudupulli	GDP	",
"Gudur Junction	GDR	",
"Gujhandi	GJD	",
"Gulabhganj	GLG	",
"Gulabpura	GBP	",
"Gulaothi	GLH	",
"Gulbarga	GR	",
"Guldhar	GUH	",
"Guledagudda Road	GED	",
"Gullaguda	GGD	",
"Gullipadu	GLU	",
"Gulzarbagh	GZH	",
"Gumada	GMDA	",
"Gumani	GMAN	",
"Gumia	GMIA	",
"Gumman	GMM	",
"Gummidipundi	GPD	",
"Gumthal	GTF	",
"Gumto	GMTO	",
"Guna	GUNA	",
"Gunadala	GALA	",
"Gundalukamma	GKM	",
"Gundardehi	GDZ	",
"Guneru Bamori	GVB	",
"Guntakal Junction	GTL	",
"Guntur Junction	GNT	",
"Guptipara	GPAE	",
"Gur Market	GRMT	",
"Guramkhedi	GMD	",
"Guraru	GRRU	",
"Gurdaspur	GSP	",
"Gurgaon	GGN	",
"Gurhi	GUX	",
"Guriya	GRI	",
"Gurla	GQL	",
"Gurnay	GRN	",
"Gurpa	GAP	",
"Gurra	GRO	",
"Gursahaiganj	GHJ	",
"Gursar Shnewala	GSW	",
"Guru Harsahai	GHS	",
"Guruvayur	GUV	",
"Guskara	GKH	",
"Guwahati	GHY	",
"Guwarighat	GRG	",
"Gwalior	GWL	",
"Gyanpur Road	GYN	",
"New Delhi	NZM	",
"Habaipur	HWX	",
"Habibganj	HBJ	",
"Habibwala	HBW	",
"Hadapsar	HDP	",
"Haddinagundu	HDD	",
"Hadmadiya	HRM	",
"Hadmatiya Junction	HM	",
"Hadyal	HYL	",
"Hafizpeta	HFZ	",
"Hafizpur	HZR	",
"Haflong Hill	HFG	",
"Hagari	HGI	",
"Haiaghat	HYT	",
"Haidarnagar	HDN	",
"Haidergarh	HGH	",
"Hajipur Junction	HJP	",
"Hakimpur	HKP	",
"Halakatta	HLKT	",
"Haldaur	HLDR	",
"Haldi Road	HLDD	",
"Haldia	HLZ	",
"Haldibari	HDB	",
"Haldipada	HIP	",
"Haldwani	HDW	",
"Halisahar	HLR	",
"Halvad	HVD	",
"Hamarapur	HMRR	",
"Hamira	HMR	",
"Hamirgarh	HMG	",
"Hamirpur Road	HAR	",
"Hamitonganj	HOJ	",
"Hamsavaram	HVM	",
"Hanakere	HNK	",
"Handia Khas	HDK	",
"Hansi	HNS	",
"Hansiawas	HSWS	",
"Hanuman Station	HNMN	",
"Hanumangarh Junction	HMH	",
"Hanumangarhtown	HMO	",
"Hanwant	HWT	",
"Hapa	HAPA	",
"Hapur	HPU	",
"Harangajao	HJO	",
"Harangul	HGL	",
"Haranya Kheri	HKH	",
"Harauni	HRN	",
"Harchandpur	HCP	",
"Harda	HD	",
"Hardas Bigha	HDE	",
"Hardattpur	HDT	",
"Hardoi	HRI	",
"Hardua	HDU	",
"Hargaon	HA	",
"Harichandanpur	HCNR	",
"Haridwar	HW	",
"Harihar	HRR	",
"Harinagar	HIR	",
"Harippad	HAD	",
"Haripur	HP	",
"Harischandrpur	HCR	",
"Harishanker Road	HSK	",
"Harkia Khal	HKL	",
"Harmuti	HMY	",
"Harnaut	HRT	",
"Harpalganj	HRPG	",
"Harpalpur	HPP	",
"Harrad	HRV	",
"Harrawala	HRW	",
"Harri	HRB	",
"Harsauli	HSI	",
"Harsud	HRD	",
"Harthala	HRH	",
"Hasanparthi Road	HSP	",
"Hasanpur Road	HPO	",
"Hasimara	HSA	",
"Hassan	HAS	",
"Hathbandh	HN	",
"Hathidah Junction	HTZ	",
"Hathidah Upper	HTZU	",
"Hathras City	HTC	",
"Hathras Junction	HRS	",
"Hathras Road	HTJ	",
"Hathuran	HAT	",
"Hatia	HTE	",
"Hatikhali	HTL	",
"Hatkanagale	HTK	",
"Hatpuraini	HPLE	",
"Haveri	HVR	",
"Hazaribagh Road	HZD	",
"Hbl Nagar	HBLN	",
"Hebbal	HEB	",
"Hejjala	HJL	",
"Helem	HML	",
"Hemagiri	HGR	",
"Her	HER	",
"Hijilli	HIJ	",
"Hilara	HLX	",
"Hilligrove	HLG	",
"Hilsa	HIL	",
"Himayatnagar	HEM	",
"Himmatana	HMI	",
"Himmatnagar	HMT	",
"Hinautaramban	HNM	",
"Hindaun City	HAN	",
"Hindupur	HUP	",
"Hinganghat	HGT	",
"Hingoli Deccan	HNL	",
"Hira Nagar	HRNR	",
"Hirakud	HKG	",
"Hirdagarh	HRG	",
"Hirenanduru	HQR	",
"Hirnoda	HDA	",
"Hisar	HSR	",
"Hodal	HDL	",
"Hojai	HJI	",
"Holalkere	HLK	",
"Holambi Kalan	HUK	",
"Hole Alur	HLAR	",
"Hole Narsipur	HLN	",
"Hombal	HBL	",
"Honnavar	HNA	",
"Hooghly Ghat	HYG	",
"Hosdurga Road	HSD	",
"Hoshangabad	HBD	",
"Hoshiarpur	HSX	",
"Hospet	HPT	",
"Hosur	HSRA	",
"Hotgi	HG	",
"Howbadh Jablpur	HBG	",
"Kolkata	HWH	",
"Hubli Junction	UBL	",
"Hunsihadgil	HHD	",
"Hyderabad	HYB	",
"Ib	IB	",
"Ibrahimpur	IMR	",
"Ichauli	ICL	",
"Ichchpuram	IPM	",
"Ichhapur	IP	",
"Idaplli	IPL	",
"Agra	IDH	",
"Igatpuri	IGP	",
"Ikkar	IKK	",
"Iklehra	IKR	",
"Indapur	INP	",
"Indara Junction	IAA	",
"Indargarh	IDGH	",
"Indargarh	IDG	",
"Indi Road	IDR	",
"Indore	INDB	",
"Indore Jn Mg	INDM	",
"Indrabil	IBL	",
"Ipurupalem	IPPM	",
"Iqbal Gadh	IQG	",
"Iqbalpur	IQB	",
"Iravipuram	IRP	",
"Irinjalakuda	IJK	",
"Irugur	IGU	",
"Isand	EN	",
"Isarda	ISA	",
"Isarwara	ISH	",
"Islampur	IPR	",
"Ismaila Haryana	ISM	",
"Ismailpur	IMGE	",
"Itarsi Junction	ET	",
"Itola	ITA	",
"Itwari	ITR	",
"Izzatnagar	IZN	",
"Jabalpur	JBP	",
"Jabli	JBL	",
"Jabri	JBX	",
"Jadcherla	JCL	",
"Yamunanagar	JUD	",
"Jagadhri Wshop	JUDW	",
"Jagadishpur	JGD	",
"Jagatbela	JTB	",
"Jagdalpur	JDB	",
"Jagdevwala	JDL	",
"Jagesharganj	JGJ	",
"Jagi Road	JID	",
"Jagraon	JGN	",
"Jagudan	JDN	",
"Jai Samand Road	JYM	",
"Jaipur	JP	",
"Jairamnagar	JRMG	",
"Jais	JAIS	",
"Jaisalmer	JSM	",
"Jaithari	JTI	",
"Jaitipur	JTU	",
"Jaitsar	JES	",
"Jaitwar	JTW	",
"Jajiwal	JWL	",
"Jajpur K Road	JJKR	",
"Jakhal Junction	JHL	",
"Jakhalabandha	JKB	",
"Jakhalaun	JLN	",
"Jakhanian	JKN	",
"Jakhapura	JKPR	",
"Jakhim	JHN	",
"Jakhvada	JKA	",
"Jalalganj	JLL	",
"Jalalpur Dhai	JPD	",
"Jalamb Junction	JM	",
"Jalandhar	JRC	",
"Jalandhar	JUC	",
"Jalargarh	JAG	",
"Jalesar Road	JLS	",
"Jaleswar	JER	",
"Jalgaon	JL	",
"Jalindri	JNRI	",
"Jaliya Devani	JALD	",
"Jallalabd	JBD	",
"Jalna	J	",
"Jalor	JOR	",
"Jalpaiguri	JPG	",
"Jalpaiguri Road	JPE	",
"Jalsu	JAC	",
"Jalsu Nanak	JACN	",
"Jam Jodhpur Junction	JDH	",
"Jam Wanthali	WTJ	",
"Jama	JAMA	",
"Jamalpur	JMP	",
"Jambara	JMV	",
"Jamdha	JMD	",
"Jamga	JMG	",
"Jamikunta	JMKT	",
"Jamirghata	JMQ	",
"Jammu	JAT	",
"Jamnagar	JAM	",
"Jamsar	JMS	",
"Jamtara	JMT	",
"Jamui	JMU	",
"Jamunamukh	JMK	",
"Jamunia Kalan	JMKL	",
"Janakpur Road	JNR	",
"Jandiala	JNL	",
"Jandrapeta	JAQ	",
"Jangaon	ZN	",
"Janghai Junction	JNH	",
"Jangipur Road	JRLE	",
"Jankampet Junction	JKM	",
"Janwal	JOA	",
"Jaora	JAO	",
"Japla	JPL	",
"Jaraikela	JRA	",
"Jarandeshwar	JSV	",
"Jarangdih	JAN	",
"Jargaon	JRJ	",
"Jaroli	JRLI	",
"Jarti	JRT	",
"Jarwal Road	JLD	",
"Jasidih Junction	JSME	",
"Jasra	JSR	",
"Jaswantgarh	JSH	",
"Jaswantnagar	JGR	",
"Jath Road	JTRD	",
"Jatinga	JTG	",
"Jatinga Lumpur	JGLP	",
"Jatkanhar	JTR	",
"Jatusana	JTS	",
"Jatwara	JW	",
"Jaunpur	JOP	",
"Jaunpur Junction	JNU	",
"Jawad Road	JWO	",
"Jawaharnagar	JWNR	",
"Jawaharnagar	JWHR	",
"Jawai Bandh	JWB	",
"Jawali	JAL	",
"Jayasingpur	JSP	",
"Jaynagar	JYG	",
"Jehanabad	JHD	",
"Jejuri	JJR	",
"Jeonara Ph	JONR	",
"Jeonathpur	JEP	",
"Jeruwa Khera	JRK	",
"Jetalsar Junction	JLR	",
"Jethi	JTY	",
"Jeur	JEUR	",
"Jeypore	JYP	",
"Jgmbla Kshnprm	JBK	",
"Jhajha	JAJ	",
"Jhalawar Road	JHW	",
"Jhalida	JAA	",
"Jhalwara	JLW	",
"Jhansi Junction	JHS	",
"Jhantipahari	JPH	",
"Jhapater Dhal	JTL	",
"Jhargram	JGM	",
"Jharia	JRI	",
"Jharili	JRL	",
"Jharkhandi	JKNI	",
"Jharradih	JDI	",
"Jharsuguda Junction	JSG	",
"Jhilmili	JLY	",
"Jhimri	JHMR	",
"Jhingura	JHG	",
"Jhinjhak	JJK	",
"Jhir	JHIR	",
"Jhulasan	JUL	",
"Jhunjhunun	JJN	",
"Jhunpa	JUP	",
"Jiaganj	JJG	",
"Jigna	JIA	",
"Jimidipeta	JMPT	",
"Jind Junction	JIND	",
"Jinti Road	JNTR	",
"Jiradei	ZRDE	",
"Jiradei	ZRD	",
"Jirania	JRNA	",
"Jirat	JIT	",
"Jirwan	JRWN	",
"Jitakheri	JKZ	",
"Jite	JITE	",
"Jiyapuram	JPM	",
"Jmlpr Shaikhan	JPS	",
"Jmtra Paraswara	JPV	",
"Jo Jagabor	JO	",
"Jodhpur	JU	",
"Jogal	JOL	",
"Jogbani	JBN	",
"Jogendranagar	JGNR	",
"Jogi Magra	JOM	",
"Jogighopa	JPZ	",
"Jolarpettai	JTJ	",
"Jonha	JON	",
"Jorai	JOQ	",
"Joramow	JRW	",
"Joravasan	JRS	",
"Jorawarnagar Junction	JVN	",
"Jorhat Town	JTTN	",
"Joychandi Pahar	JOC	",
"Jugaur	JRR	",
"Jugijan	JGJN	",
"Jugpura	JRG	",
"Jujumura	JUJA	",
"Jukehi	JKE	",
"Julana	JNA	",
"Junagadh Junction	JND	",
"Jung Bahadurgnj	JBG	",
"Junnor Deo	JNO	",
"Jutogh	JTO	",
"Jwalapur	JWP	",
"Kabakaputtur	KBPR	",
"Hyderabad	KCG	",
"Kachewani	KWN	",
"Kachhia Bridge	KCO	",
"Kachnara Road	KCNR	",
"Kachujor	KOX	",
"Kadakavur	KVU	",
"Kadakola	KDO	",
"Kadalundi	KN	",
"Kadambur	KDU	",
"Kadavakuduru	KVDU	",
"Kadaynallur	KDNL	",
"Kadethan	KDTN	",
"Kadipur	KDQ	",
"Kadiri	KRY	",
"Kadiyan	KYM	",
"Kadur	DRU	",
"Kafurpur	KFPR	",
"Kahalgaon	CLG	",
"Kahet	KRAI	",
"Kahiliya	KH	",
"Kaialsa	KIV	",
"Kaikolur	KKLR	",
"Kaikoram	KKRM	",
"Kailahat	KYT	",
"Kailasapuram	KLPM	",
"Kaima	KMA	",
"Kaimganj	KMJ	",
"Kairla	KAI	",
"Kaithal	KLE	",
"Kaithalkuchi	KTCH	",
"Kajgaon	KJ	",
"Kajoragram	KJME	",
"Kajra	KJH	",
"Kajrat Nawadih	KYF	",
"Kakapora	KAPE	",
"Kakarghatti	KKHT	",
"Kakinada Port	COA	",
"Kakinada Town	CCT	",
"Kakirigumma	KKGM	",
"Kaklur	KKLU	",
"Kakori	KKJ	",
"Kala Akhar	KQE	",
"Kalachand	KQI	",
"Kaladehi	KDHI	",
"Kalamb Road	KMRD	",
"Kalamboli	KLMC	",
"Kalamboli	KLMG	",
"Kalamna	KAV	",
"Kalana	KALN	",
"Kalanaur Kalan	KLNK	",
"Kalanwali	KNL	",
"Kalapipal	KPP	",
"Kaldhari	KLDI	",
"Kalgupur	KCP	",
"Kalhar	KAH	",
"Kali Sindh	KSH	",
"Kalian Chak	KXE	",
"Kanpur	KAP	",
"Kalinarynpur Junction	KLNP	",
"Kalipahari	KPK	",
"Kaliyanganj	KAJ	",
"Kalka	KLK	",
"Kalkund	KKD	",
"Kallakkudi Plgh	KKPM	",
"Kallal	KAL	",
"Kalligudi	KGD	",
"Kallkiri	KCI	",
"Kalluru	KLU	",
"Kalmeshwar	KSWR	",
"Kalmitar	KLTR	",
"Kalol	KLL	",
"Kalpi	KPI	",
"Kalsur	KVS	",
"Kalunga	KLG	",
"Kalupara Ghat	KAPG	",
"Mumbai	KYN	",
"Kalyani	KYI	",
"Kalyanpur Road	KPRD	",
"Kamakhya	KYQ	",
"Kamakhyaguri	KAMG	",
"Kamalapuram	KKM	",
"Kamalganj	KLJ	",
"Kamalnagar	KMNR	",
"Kamalpurgram	KLPG	",
"Kamalur	KMLR	",
"Kamarbandha Ali	KXL	",
"Kamareddi	KMC	",
"Kamarkundu	KQU	",
"Kamasamudram	KSM	",
"Kamathe	KMAH	",
"Kamli	KMLI	",
"Kamptee	KP	",
"Kampur	KWM	",
"Kamrup Khetri	KKET	",
"Kamshet	KMST	",
"Kamtaul	KML	",
"Kanakpura	KKU	",
"Kanalas Junction	KNLS	",
"Kanas Road	KASR	",
"Kanasar	KNSR	",
"Kanauta	KUT	",
"Kanchipuram	CJ	",
"Kanchrapara	KPA	",
"Kandaghat	KDZ	",
"Kandarpur	KDRP	",
"Kandel Road	KDLR	",
"Kandra	KND	",
"Kandrori	KNDI	",
"Kanginhal	KGX	",
"Kanhaipur	KNHP	",
"Kanhangad	KZE	",
"Kanhegaon	KNGN	",
"Kanil	KANJ	",
"Kanina Khas	KNNK	",
"Kaniwara	KWB	",
"Kaniyapuram	KXP	",
"Kanjari Boriyav	KBRV	",
"Kankaha	KKAH	",
"Kankanadi	KNKD	",
"Kankather	KHE	",
"Kankavali	KKW	",
"Kanki	KKA	",
"Kankinara	KNR	",
"Kannapuram	KPQ	",
"Kannauj	KJN	",
"Kannur	CAN	",
"Kanoh	KANO	",
"Kanpur	CPA	",
"Kanpur	CNB	",
"Kanshbahal	KXN	",
"Kansrao	QSR	",
"Kantabanji	KBJ	",
"Kantadih	KTD	",
"Kantakapalle	KPL	",
"Kanth	KNT	",
"Kanthan Junction	KNHN	",
"Kanthi P H	KATI	",
"Kanwalpura	KIW	",
"Kanwat	KAWT	",
"Kanyakumari	CAPE	",
"Kapan	KPNA	",
"Kapasan	KIN	",
"Kapilas Road	KIS	",
"Kappil	KFI	",
"Kapren	KPZ	",
"Kapseti	KEH	",
"Kaptanganj Junction	CPJ	",
"Kapurdha Halt	KPDH	",
"Kapurthala	KXH	",
"Karaboh	KRBO	",
"Karad	KRD	",
"Karagola Road	CRR	",
"Karaikal	KIK	",
"Karaikkudi Junction	KKDI	",
"Karaila Road Junction	KRLR	",
"Karajgi	KJG	",
"Karak Bel	KKB	",
"Karakavalasa	KVLS	",
"Karambeli	KEB	",
"Karamelaram	CRLM	",
"Karamnasa	KMS	",
"Karamtola	KRMA	",
"Karanjadi	KFD	",
"Karanjgaon	KAJG	",
"Karanpur Ato	KPTO	",
"Karauta	KWO	",
"Karavadi	KRV	",
"Karbigwan	KBN	",
"Karchana	KCN	",
"Karchha	KDHA	",
"Kareli	KY	",
"Karengi	KEG	",
"Karepalli	KRA	",
"Karepur	KRPR	",
"Kargi Road	KGB	",
"Karhiya Bhadeli	KYX	",
"Kariganuru	KGW	",
"Karimganj Junction	KXJ	",
"Karimnagar	KRMR	",
"Karimuddin Pur	KMDR	",
"Karisath	KRS	",
"Mumbai	KJT	",
"Karjoda	KRJD	",
"Karkeli	KKI	",
"Karkheli	KEK	",
"Karmad	KMV	",
"Goa	KRMI	",
"Karna	KAR	",
"Karnal	KUN	",
"Karonda	KOA	",
"Karonji	KJZ	",
"Karpurigram	KPGM	",
"Kartarpur	KRE	",
"Karunagapalli	KPY	",
"Karur	KRR	",
"Karwar	KAWR	",
"Kasara	KSRA	",
"Kasaragod	KGQ	",
"Kasganj	KSJ	",
"Kashi	KEI	",
"Kashi Chak	KSC	",
"Kashipur	KPV	",
"Kashipura Sarar	KSPR	",
"Kashti	KSTH	",
"Kasim Kota Halt	KCH	",
"Kasimkota	KSK	",
"Kasimpur	KCJ	",
"Kastha	KSTA	",
"Kasu	KASU	",
"Katakhal Junction	KTX	",
"Katareah	KTRH	",
"Kathal Pukhuri	KTPR	",
"Kathara Road	KTRR	",
"Kathghar	KGF	",
"Kathgodam	KGM	",
"Kathleeghat	KEJ	",
"Kathua	KTHU	",
"Katihar Junction	KIR	",
"Katni	KTE	",
"Katni Murwara	KMZ	",
"Katni South	KTES	",
"Katol	KATL	",
"Katora	KTO	",
"Katpadi	KPD	",
"Katphal	KFH	",
"Katra	KEA	",
"Katrasgarh	KTH	",
"Katwa	KWAE	",
"Kaurha	KUF	",
"Kavali	KVZ	",
"Kavathe Mahankl	KVK	",
"Kavutaram	KVM	",
"Kawargaon	KWGN	",
"Kayalpattinam	KZY	",
"Kayamsar	QMRS	",
"Kayankulam Junction	KYJ	",
"Kayar	KAYR	",
"Kazhakuttam	KZK	",
"Kazipet Junction	KZJ	",
"Kcg Falaknuma	FM	",
"Keckhi	KCKI	",
"Kedgaon	KDG	",
"Kelod	KLOD	",
"Kelva Road	KLV	",
"Kem	KEM	",
"Kemri	KEMR	",
"Kendposi	KNPS	",
"Kendrapara Road	KNPR	",
"Kendujhargarh	KDJR	",
"Kendukana	KDKN	",
"Kengeri	KGI	",
"Keolari	KLZ	",
"Kesamudram	KDM	",
"Kesavaram	KSVM	",
"Keshavganj	KVJ	",
"Keshod	KSD	",
"Keshorai Patan	KPTN	",
"Kesinga	KSNG	",
"Kesri Singhpur	KESR	",
"Ketti	KXT	",
"Keutguda	KTGA	",
"Khachrod	KUH	",
"Khada	KZA	",
"Khadapa	KDPA	",
"Pune	KK	",
"Khaga	KGA	",
"Khagaria Junction	KGG	",
"Khagraghat Road	KGLE	",
"Khairar Junction	KID	",
"Khairatabad Dcn	KQD	",
"Khairthal	KRH	",
"Khajauli	KJI	",
"Khajuraho	KURJ	",
"Khajwana	KJW	",
"Khalari	KLRE	",
"Khalilabad	KLD	",
"Khalilpur	KIP	",
"Khalispur	KSF	",
"Khallikot	KIT	",
"Khaltipur	KTJ	",
"Khamargachhi	KMAE	",
"Khambhaliya	KMBL	",
"Khamgaon	KMN	",
"Khammam	KMT	",
"Khana Junction	KAN	",
"Khanapur	KNP	",
"Khandala	KAD	",
"Khandbaara	KBH	",
"Khandip	KNDP	",
"Khandwa	KNW	",
"Khanna	KNN	",
"Khanna Banjari	KHBJ	",
"Khanyan	KHN	",
"Khapri Kheda	KPKD	",
"Kharagpur Junction	KGP	",
"Kharak	KHRK	",
"Kharia Khangarh	KXG	",
"Khariar Road	KRAR	",
"Kharsaliya	KRSA	",
"Kharsia	KHS	",
"Kharwa	KRW	",
"Kharwa Chanda	KRCD	",
"Khat	KHAT	",
"Khatauli	KAT	",
"Khatgaon	KHTG	",
"Khatima	KHMA	",
"Khatipura	KWP	",
"Khatu	KHTU	",
"Khed	KHED	",
"Kheduli	KQW	",
"Khemli	KLH	",
"Khera Kalan	KHKN	",
"Kheri Salwa	KSW	",
"Kheril	KL	",
"Kheta Sarai	KS	",
"Khileriyan	KLYN	",
"Khimel	KZQ	",
"Khinaniyan	KNNA	",
"Khirkiya	KKN	",
"Khirsadoh Junction	KUX	",
"Khodiyar	KHDB	",
"Khodiyar	KHD	",
"Khodri	KOI	",
"Khoirabari	KBY	",
"Khongsara	KGS	",
"Khorason Road	KRND	",
"Khori	KORI	",
"Khudiram B Pusa	PUV	",
"Khudiram B Pusa	KRBP	",
"Khumtai	KUTI	",
"Khunkhuna	KKNA	",
"Khurai	KYE	",
"Khurda Road Junction	KUR	",
"Khurdpur	KUPR	",
"Khurhand	KHU	",
"Khurial	KWE	",
"Khurja City	KJY	",
"Khurja Junction	KRJ	",
"Khusropur	KOO	",
"Khutaha	KTHA	",
"Khutbav	KTT	",
"Kichha	KHH	",
"Kikakui Road	KKRD	",
"Kila Kadaiyam	KKY	",
"Kila Raipur	QRP	",
"Kilikollur	KLQ	",
"Kim	KIM	",
"Kinwat	KNVT	",
"Kirakat	KCT	",
"Kirandul	KRDL	",
"Kiraoli	KLB	",
"Kiratgarh	KRTH	",
"Kiratpur	KART	",
"Kirihrapur	KER	",
"Kirloskarvadi	KOV	",
"Kiroda	KRC	",
"Kirodimalnagar	KDTR	",
"Kishanganj	KNE	",
"Kishangarh	KSG	",
"Kishanpur	KSP	",
"Kishengarh Blws	KGBS	",
"Kisoni	KONY	",
"Kistamsettipali	KSTE	",
"Kita	KITA	",
"Kiul Junction	KIUL	",
"Kivarli	KWI	",
"Kiwar Khed	HKR	",
"Trivandrum	KCVL	",
"Kodaganur	KAG	",
"Kodaikanal Road	KQN	",
"Kodavaluru	KJJ	",
"Koderma	KQR	",
"Kodi	KODI	",
"Kodiyar Mandir	KDMR	",
"Kodumudi	KMD	",
"Koduru	KOU	",
"Koelwar	KWR	",
"Kohir Deccan	KOHR	",
"Koiripur	KEPR	",
"Kokrajhar	KOJ	",
"Kolad	KOL	",
"Kolakalur	KLX	",
"Kolanukonda	KAQ	",
"Kolaras	KLRS	",
"Kolayat	KLYT	",
"Kolda	KFF	",
"Kolkata	CP	",
"Kolkata	KOAA	",
"Kollam Junction	QLN	",
"Kollikhutaha	KKTA	",
"Kolnur	KOLR	",
"Kolvagram	KVGM	",
]